Journal/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trades.urls')),
    path('spot', include('spot_bag.urls')),
]

spot_bag/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "spot_bag"
urlpatterns = [
    path("", views.home_page, name="home_page"),
    # path("upload/", views.upload_trades, name="trades"),
]

trades/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "trades"
urlpatterns = [
    path("", views.home_page, name="home_page"),
    path("upload/", views.upload_trades, name="trades"),
]

spot_bag/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.


class SpotBag(models.Model):
    SIDE_CHOICES = (("long", "LONG"), ("short", "SHORT"))
    ticker = models.CharField(null=False, blank=False, max_length=10)
    side = models.CharField(null=False, blank=False, max_length=5, choices=SIDE_CHOICES)

    entry = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=9)
    stop_loss = models.DecimalField(
        null=True, blank=True, max_digits=15, decimal_places=9
    )
    take_profit = models.DecimalField(
        null=True, blank=True, max_digits=15, decimal_places=9
    )
    trade_exit = models.DecimalField(
        null=True, blank=True, max_digits=15, decimal_places=9
    )
    pnl = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    rr = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    tags = models.CharField(null=True, blank=True, max_length=20)
    image = models.ImageField(null=True, blank=True)
    comments = models.CharField(null=True, blank=True, max_length=1000)

    def __str__(self) -> str:
        return self.ticker

    def save(self, *args, **kwargs):
        # set ticker to uppercase
        self.ticker = self.ticker.upper()

        # calculate pnl and rr for trades
        if (
            self.trade_exit
            and self.entry
            and self.stop_loss
            and self.take_profit
            and self.side
        ):
            cal = calculate(
                entry=self.entry,
                sl=self.stop_loss,
                tp=self.take_profit,
                _exit=self.trade_exit,
                side=self.side,
            )
            self.pnl = round(cal["pnl"], 2)
            self.rr = round(cal["rr"], 2)

        print(self.pnl, self.rr)

        super().save(*args, **kwargs)


def calculate(entry, sl, tp, _exit, side):
    pnl = 0
    rr = 0
    if side == "long":
        pnl = _exit - entry
        rr = (tp - entry) / (entry - sl)

    if side == "short":
        pnl = entry - _exit
        rr = (entry - tp) / (sl - entry)

    return {"pnl": pnl, "rr": rr}

trades/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.


class Trades(models.Model):
    SIDE_CHOICES = (("long", "LONG"), ("short", "SHORT"))
    ticker = models.CharField(null=False, blank=False, max_length=10)
    side = models.CharField(null=False, blank=False, max_length=5, choices=SIDE_CHOICES)

    entry = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=9)
    stop_loss = models.DecimalField(
        null=True, blank=True, max_digits=15, decimal_places=9
    )
    take_profit = models.DecimalField(
        null=True, blank=True, max_digits=15, decimal_places=9
    )
    trade_exit = models.DecimalField(
        null=True, blank=True, max_digits=15, decimal_places=9
    )
    pnl = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    rr = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    tags = models.CharField(null=True, blank=True, max_length=20)
    image = models.ImageField(null=True, blank=True)
    comments = models.CharField(null=True, blank=True, max_length=1000)

    def __str__(self) -> str:
        return self.ticker

    def save(self, *args, **kwargs):
        # set ticker to uppercase
        self.ticker = self.ticker.upper()

        # calculate pnl and rr for trades
        if (
            self.trade_exit
            and self.entry
            and self.stop_loss
            and self.take_profit
            and self.side
        ):
            cal = calculate(
                entry=self.entry,
                sl=self.stop_loss,
                tp=self.take_profit,
                _exit=self.trade_exit,
                side=self.side,
            )
            self.pnl = round(cal["pnl"], 2)
            self.rr = round(cal["rr"], 2)

        print(self.pnl, self.rr)

        super().save(*args, **kwargs)


def calculate(entry, sl, tp, _exit, side):
    pnl = 0
    rr = 0
    if side == "long":
        pnl = _exit - entry
        rr = (tp - entry) / (entry - sl)

    if side == "short":
        pnl = entry - _exit
        rr = (entry - tp) / (sl - entry)

    return {"pnl": pnl, "rr": rr}

spot_bag/forms.py
from django import forms
from django.forms import widgets

spot_bag/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, HttpResponse
from .models import SpotBag

# Create your views here.
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
import json

# from .serializer import TradeSerializer


def home_page(request, *args, **kwargs):
    context = {"spot" : True}
    print(request.method)
    return render(request, "base.html", context=context)


# elif request.method == 'POST' :


@api_view(["POST"])
def upload_trades(request, *args, **kwargs):
    pass

trades/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden
from .models import Trades

# Create your views here.
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
import json

from .serializer import TradeSerializer


def home_page(request, *args, **kwargs):
    if request.method == "GET":
        all_trades = Trades.objects.all()
        context = {"trades": all_trades, "ledger" : True}
        print(request.method)
        return render(request, "base.html", context=context)


# elif request.method == 'POST' :


@api_view(["POST"])
def upload_trades(request, *args, **kwargs):
    # if request.method == "POST":
    #     data = json.loads(request.body)
    #     entry = data.get("entry", "")
    #     _exit = data.get("exit", "")
    #     ticker = data.get("ticker")
    #     side = data.get("side")
    #     stop_loss = data.get("stop_loss", "")
    #     take_profit = data.get("take_profit")
    #     pnl = data.get("pnl", "")
    #     rr = data.get("rr", "")
    #     tags = data.get("tags", "")
    #     comment = data.get("comment", "")
    #     if entry == "":
    #         return HttpResponseForbidden("The ENTRY field can not be empty!")
    #     if ticker == "":
    #         return HttpResponseForbidden("The TICKER field can not be empty!")

    # serializer = TradeSerializer(data=json.loads(request.body))
    serializer = TradeSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()
        print("form was valid")
        return Response({"message": "Upload successful"})
    else:
        errors = serializer.errors
        error_message = {}
        for k, v in errors.items():
            error_message[k] = f"{v[0]}"
        print(error_message)

        return Response(error_message, status=400)

spot_bag/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% endblock content %}

spot_bag/templates/partials/_trades_table.html
{% load static %}

<link type="text/css" rel="stylesheet" href="{% static 'css/_trades_table.css' %}">


<!-- Erro pop up -->
<div id="error_popup">

</div>

<!-- Main Trading entries -->
<div class="table-container">
    <table class="styled-table">
        <thead class="entries-table-head">
            <tr>
                <th>
                    Ticker
                </th>
                <th>
                    Side
                </th>

                <th>
                    Entry Price
                </th>
                <th>
                    Stop Loss
                </th>
                <th>
                    Take Profit
                </th>
                <th>
                    Exit Price
                </th>
                <th>
                    PnL
                </th>
                <th>
                    R:R
                </th>

                <th>
                    Tags
                </th>
                <th>
                    Image
                </th>
                <th>
                    Comments
                </th>
            </tr>
        </thead>

        <tbody class="entries-table-body">
            {% for trade in trades %}

            <tr class="table-rows" onclick="toggle_comments(this)">
                <td>
                    {{ trade.ticker}}
                </td>

                <td>
                    {{ trade.side }}
                </td>

                <td>
                    {{ trade.entry }}
                </td>

                <td>
                    {{ trade.stop_loss }}
                </td>

                <td>
                    {{ trade.take_profit }}
                </td>
                <td>
                    {{ trade.trade_exit }}
                </td>
                <td>
                    {{ trade.pnl }}
                </td>
                <td>
                    {{ trade.rr }}
                </td>
                <td>
                    {{ trade.tags }}
                </td>
                <td>
                    <img alt="None" src="{{ trade.image }}">
                </td>
                <td id="comment">
                    {{ trade.comments }}
                </td>
            </tr>
            {% endfor %}


            <form method="post" action="{% url 'trades' %}" id="tradeForm">
                {% csrf_token %}
                <tr class="table-rows">
                    <td><input type="text" name="ticker" placeholder="TICKER"></td>
                    <td>
                        <select>
                            <option value="long">LONG</option>
                            <option value="short">SHORT</option>
                        </select>
                    </td>
                    <td><input type="text" name="entry_price" placeholder="ENTRY PRICE"></td>
                    <td><input type="text" name="stop_loss" placeholder="STOP LOSS"></td>
                    <td><input type="text" name="take_profit" placeholder="TAKE PROFIT"></td>
                    <td><input type="text" name="exit_price" placeholder="EXIT PRICE"></td>
                    <td><input type="text" name="pnl" placeholder="PNL"></td>
                    <td><input type="text" name="rr" placeholder="RR"></td>
                    <td><input type="text" name="tags" placeholder="TAGS"></td>
                    <td><input type="text" name="image" placeholder="IMAGE"></td>
                    <td id="submit_trade"><input type="text" name="comment" placeholder="COMMENT">
                        <input type="submit" value="Submit">
                        <!-- <span id="submit_button_span">
                            <button value="submit" type="submit">submit</button>
                        </span> -->
                    </td>
                </tr>
            </form>



        </tbody>
    </table>
</div>

<div id="uploadtrades-container">


</div>











<script type="text/javascript" src="{% static 'js/_trades_table.js' %}"> </script>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}">

</head>


<body>
    <!-- Header of the page -->
    <header>
        {% include 'partials/header.html' %}
    </header>


    <main class="full_page" id="full_page">
        <div class="sidebar">
            <!-- Side Bar for the page -->
            {% include 'partials/_sidebar.html' %}
        </div>
        <div class="collapse-button-container">
            <button class="collapse-button" onclick="myFunction()">Collapse</button>
        </div>

				<!-- if ledger (futures) is passed to context render the futures table elseif spot is passed render spots tables -->
				{% if ledger %}
        <div class="ledger">
					{% include 'partials/futures_trades_table.html' with trades=trades %}
        </div>
				{% elif spot %}
					{% include 'partials/spot_table.html' %}
				{% endif %}

        {% block content %}

        {% endblock content %}
    </main>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% endblock content %}

templates/partials/_sidebar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/_sidebar.css' %}">

<p> 
<a href="{% url 'spot_bag:home_page' %}">Spot</a>
</p>
<p> 
<a href="{% url 'trades:home_page' %}">Futures</a>
</p>

<script type="text/javascript" src="{% static 'js/_sidebar.js' %}"></script>

templates/partials/_trades_table.html
{% load static %}

<link type="text/css" rel="stylesheet" href="{% static 'css/_trades_table.css' %}">


<!-- Erro pop up -->
<div id="error_popup">

</div>

<!-- Main Trading entries -->
<div class="table-container">
    <table class="styled-table">
        <thead class="entries-table-head">
            <tr>
                <th>
                    Ticker
                </th>
                <th>
                    Side
                </th>

                <th>
                    Entry Price
                </th>
                <th>
                    Stop Loss
                </th>
                <th>
                    Take Profit
                </th>
                <th>
                    Exit Price
                </th>
                <th>
                    PnL
                </th>
                <th>
                    R:R
                </th>

                <th>
                    Tags
                </th>
                <th>
                    Image
                </th>
                <th>
                    Comments
                </th>
            </tr>
        </thead>

        <tbody class="entries-table-body">
            {% for trade in trades %}

            <tr class="table-rows" onclick="toggle_comments(this)">
                <td>
                    {{ trade.ticker}}
                </td>

                <td>
                    {{ trade.side }}
                </td>

                <td>
                    {{ trade.entry }}
                </td>

                <td>
                    {{ trade.stop_loss }}
                </td>

                <td>
                    {{ trade.take_profit }}
                </td>
                <td>
                    {{ trade.trade_exit }}
                </td>
                <td>
                    {{ trade.pnl }}
                </td>
                <td>
                    {{ trade.rr }}
                </td>
                <td>
                    {{ trade.tags }}
                </td>
                <td>
                    <img alt="None" src="{{ trade.image }}">
                </td>
                <td id="comment">
                    {{ trade.comments }}
                </td>
            </tr>
            {% endfor %}


            <form method="post" action="{% url 'trades:trades' %}" id="tradeForm">
                {% csrf_token %}
                <tr class="table-rows">
                    <td><input type="text" name="ticker" placeholder="TICKER"></td>
                    <td>
                        <select>
                            <option value="long">LONG</option>
                            <option value="short">SHORT</option>
                        </select>
                    </td>
                    <td><input type="text" name="entry_price" placeholder="ENTRY PRICE"></td>
                    <td><input type="text" name="stop_loss" placeholder="STOP LOSS"></td>
                    <td><input type="text" name="take_profit" placeholder="TAKE PROFIT"></td>
                    <td><input type="text" name="exit_price" placeholder="EXIT PRICE"></td>
                    <td><input type="text" name="pnl" placeholder="PNL"></td>
                    <td><input type="text" name="rr" placeholder="RR"></td>
                    <td><input type="text" name="tags" placeholder="TAGS"></td>
                    <td><input type="text" name="image" placeholder="IMAGE"></td>
                    <td id="submit_trade"><input type="text" name="comment" placeholder="COMMENT">
                        <input type="submit" value="Submit">
                        <!-- <span id="submit_button_span">
                            <button value="submit" type="submit">submit</button>
                        </span> -->
                    </td>
                </tr>
            </form>



        </tbody>
    </table>
</div>

<div id="uploadtrades-container">


</div>











<script type="text/javascript" src="{% static 'js/_trades_table.js' %}"> </script>

templates/partials/futures_trades_table.html
{% load static %}

<link type="text/css" rel="stylesheet" href="{% static 'css/futures_trades_table.css' %}">


<!-- Erro pop up -->
<div id="error_popup">

</div>

<!-- Main Trading entries -->
<div class="table-container">
    <table class="styled-table">
        <thead class="entries-table-head">
            <tr>
                <th>
                    Ticker
                </th>
                <th>
                    Side
                </th>

                <th>
                    Entry Price
                </th>
                <th>
                    Stop Loss
                </th>
                <th>
                    Take Profit
                </th>
                <th>
                    Exit Price
                </th>
                <th>
                    PnL
                </th>
                <th>
                    R:R
                </th>

                <th>
                    Tags
                </th>
                <th>
                    Image
                </th>
                <th>
                    Comments
                </th>
            </tr>
        </thead>

        <tbody class="entries-table-body">
            {% for trade in trades %}

            <tr class="table-rows" onclick="toggle_comments(this)">
                <td>
                    {{ trade.ticker}}
                </td>

                <td>
                    {{ trade.side }}
                </td>

                <td>
                    {{ trade.entry }}
                </td>

                <td>
                    {{ trade.stop_loss }}
                </td>

                <td>
                    {{ trade.take_profit }}
                </td>
                <td>
                    {{ trade.trade_exit }}
                </td>
                <td>
                    {{ trade.pnl }}
                </td>
                <td>
                    {{ trade.rr }}
                </td>
                <td>
                    {{ trade.tags }}
                </td>
                <td>
                    <img alt="None" src="{{ trade.image }}">
                </td>
                <td id="comment">
                    {{ trade.comments }}
                </td>
            </tr>
            {% endfor %}


            <form method="post" action="{% url 'trades:trades' %}" id="tradeForm">
                {% csrf_token %}
                <tr class="table-rows">
                    <td><input type="text" name="ticker" placeholder="TICKER"></td>
                    <td>
                        <select>
                            <option value="long">LONG</option>
                            <option value="short">SHORT</option>
                        </select>
                    </td>
                    <td><input type="text" name="entry_price" placeholder="ENTRY PRICE"></td>
                    <td><input type="text" name="stop_loss" placeholder="STOP LOSS"></td>
                    <td><input type="text" name="take_profit" placeholder="TAKE PROFIT"></td>
                    <td><input type="text" name="exit_price" placeholder="EXIT PRICE"></td>
                    <td><input type="text" name="pnl" placeholder="PNL"></td>
                    <td><input type="text" name="rr" placeholder="RR"></td>
                    <td><input type="text" name="tags" placeholder="TAGS"></td>
                    <td><input type="text" name="image" placeholder="IMAGE"></td>
                    <td id="submit_trade"><input type="text" name="comment" placeholder="COMMENT">
                        <input type="submit" value="Submit">
                        <!-- <span id="submit_button_span">
                            <button value="submit" type="submit">submit</button>
                        </span> -->
                    </td>
                </tr>
            </form>



        </tbody>
    </table>
</div>

<div id="uploadtrades-container">


</div>











<script type="text/javascript" src="{% static 'js/futures_trades_table.js' %}"> </script>

templates/partials/header.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">

<h1 class="header_name">ZEAL</h1>

templates/partials/spot_table.html
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'css/futures_trades_table.css' %}">

<!-- Erro pop up -->
<div id="error_popup">
</div>

<!-- Main Trading entries -->
<div class="table-container">
    <table class="styled-table">
        <thead class="entries-table-head">
            <tr>
                <th>
                    Ticker
                </th>
                <th>
                    Side
                </th>

                <th>
                    Entry Price
                </th>
                <th>
                    Stop Loss
                </th>
                <th>
                    Take Profit
                </th>
                <th>
                    Exit Price
                </th>
                <th>
                    PnL
                </th>
                <th>
                    R:R
                </th>

                <th>
                    Tags
                </th>
                <th>
                    Image
                </th>
                <th>
                    Comments
                </th>
            </tr>
        </thead>

        <tbody class="entries-table-body">
            {% for trade in trades %}

            <tr class="table-rows" onclick="toggle_comments(this)">
                <td>
                    {{ trade.ticker}}
                </td>

                <td>
                    {{ trade.side }}
                </td>

                <td>
                    {{ trade.entry }}
                </td>

                <td>
                    {{ trade.stop_loss }}
                </td>

                <td>
                    {{ trade.take_profit }}
                </td>
                <td>
                    {{ trade.trade_exit }}
                </td>
                <td>
                    {{ trade.pnl }}
                </td>
                <td>
                    {{ trade.rr }}
                </td>
                <td>
                    {{ trade.tags }}
                </td>
                <td>
                    <img alt="None" src="{{ trade.image }}">
                </td>
                <td id="comment">
                    {{ trade.comments }}
                </td>
            </tr>
            {% endfor %}


            <form method="post" action="{% url 'trades:trades' %}" id="tradeForm">
                {% csrf_token %}
                <tr class="table-rows">
                    <td><input type="text" name="ticker" placeholder="TICKER"></td>
                    <td>
                        <select>
                            <option value="long">LONG</option>
                            <option value="short">SHORT</option>
                        </select>
                    </td>
                    <td><input type="text" name="entry_price" placeholder="ENTRY PRICE"></td>
                    <td><input type="text" name="stop_loss" placeholder="STOP LOSS"></td>
                    <td><input type="text" name="take_profit" placeholder="TAKE PROFIT"></td>
                    <td><input type="text" name="exit_price" placeholder="EXIT PRICE"></td>
                    <td><input type="text" name="pnl" placeholder="PNL"></td>
                    <td><input type="text" name="rr" placeholder="RR"></td>
                    <td><input type="text" name="tags" placeholder="TAGS"></td>
                    <td><input type="text" name="image" placeholder="IMAGE"></td>
                    <td id="submit_trade"><input type="text" name="comment" placeholder="COMMENT">
                        <input type="submit" value="Submit">
                        <!-- <span id="submit_button_span">
                            <button value="submit" type="submit">submit</button>
                        </span> -->
                    </td>
                </tr>
            </form>



        </tbody>
    </table>
</div>

<div id="uploadtrades-container">


</div>











<script type="text/javascript" src="{% static 'js/futures_trades_table.js' %}"> </script>